name: Goimports
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Install goimports
        run: go get golang.org/x/tools/cmd/goimports

      - name: goimports
        run: goimports -l ./..
